import { atom } from 'nanostores';

export type Language = 'SLO' | 'ENG' | 'GER';

export const languageStore = atom<Language>('SLO');

export const translations = {
  SLO: {
    heroTitle1: "Operativna inteligenca za",
    heroTitle2: "delovno intenzivna podjetja.",
    heroSubtitle: "Z močjo umetne inteligence avtomatiziramo kadrovske procese in optimiziramo operativne vire v realnem času.",
    beta: "Zaprta Beta",
    partnerLink: "Prijava za partnerje 🔒",
    featureTitle: "Elixiti možgani",
    featureDesc1: "je operativna inteligenca za delovno intenzivna podjetja.",
    featureDesc2: "Odsotnost zaposlenih v teh podjetjih dnevno dosega 15-20% delovne sile zaradi bolniških in dopustov, kar vodjem pogosto vzame več kot 30% delovnega časa za ročno nadomeščanje. Posledica so operativne napake in dodatni stroški.",
    validation: "Problem smo validirali z več kot 30 razgovori. Interes za pilotno uporabo so potrdila podjetja iz različnih držav sveta, kar potrjuje globalni potencial.",
    footer: "© 2026 Elixiti d.o.o. | Rešitev se trenutno testira v zaprti beta fazi pri strateških partnerjih.",
    contact: "Kontakt:",
    tableTitle: "Pregled javnih razpisov za čiščenje v Sloveniji",
    tableDesc: "Avtomatizirano spremljanje podatkov s portala e-Naročanje v realnem času: celovit pregled nad aktualnimi razpisi, sodelujočimi podjetji in izbranimi zmagovalci na področju čiščenja.",
    // Funnel Translations
    f1: "1. PROBLEM / VHOD",
    f1a: "ANALITIKA &",
    f1b: "DOKUMENTI",
    f1c: "POMANJKANJE",
    f1d: "KADRA",
    f1e: "PRAVNA",
    f1f: "TVEGANJA",
    f2: "2. REŠITEV (ELIXITI AI MOŽGANI)",
    f2a: "X-RAY VID",
    f3: "3. ČLOVEŠKA ODLOČITEV",
    f3a: "(POTRDITEV)",
    f4: "4. AGENTSKA IZVEDBA",
    f4a: "(AVTOMATIZACIJA)",
    res1a: "VEČJI",
    res1b: "PRIHODKI",
    res2a: "MANJŠE",
    res2b: "TVEGANJE",
    res3a: "PRIHRANEK",
    res3b: "ČASA (HR)"
  },
  ENG: {
    heroTitle1: "Operational Intelligence for",
    heroTitle2: "Workforce-Intensive Companies.",
    heroSubtitle: "Automating HR processes and optimizing operational resources in real time with the power of Artificial Intelligence.",
    beta: "Closed Beta",
    partnerLink: "Partner Access 🔒",
    featureTitle: "Elixiti Brain",
    featureDesc1: "is operational intelligence for workforce-intensive companies.",
    featureDesc2: "Employee absenteeism in these companies reaches 15-20% of the workforce daily due to sick leave and vacations, often taking up more than 30% of managers' time for manual replacement. This results in operational errors and additional costs.",
    validation: "We validated the problem through more than 30 interviews. Interest in pilot use was confirmed by companies from different countries worldwide, confirming the global potential.",
    footer: "© 2026 Elixiti d.o.o. | The solution is currently being tested in a closed beta phase with strategic partners.",
    contact: "Contact:",
    tableTitle: "Overview of Public Cleaning Tenders in Slovenia",
    tableDesc: "Automated real-time monitoring of data from the e-Naročanje portal: a comprehensive overview of current tenders, participating companies, and selected winners in the cleaning sector.",
    // Funnel Translations
    f1: "1. PROBLEM / INPUT",
    f1a: "ANALYTICS &",
    f1b: "DOCUMENTS",
    f1c: "STAFF",
    f1d: "SHORTAGE",
    f1e: "LEGAL",
    f1f: "RISKS",
    f2: "2. SOLUTION (ELIXITI AI BRAIN)",
    f2a: "X-RAY VISION",
    f3: "3. HUMAN DECISION",
    f3a: "(CONFIRMATION)",
    f4: "4. AGENTIC EXECUTION",
    f4a: "(AUTOMATION)",
    res1a: "INCREASED",
    res1b: "REVENUE",
    res2a: "REDUCED",
    res2b: "LEGAL RISK",
    res3a: "TIME",
    res3b: "SAVINGS (HR)"
  },
  GER: {
    heroTitle1: "Operative Intelligenz für",
    heroTitle2: "personalintensive Unternehmen.",
    heroSubtitle: "Automatisierung von HR-Prozessen und Echtzeit-Optimierung operativer Ressourcen durch die Kraft der Künstlichen Intelligenz.",
    beta: "Geschlossene Beta",
    partnerLink: "Partner-Anmeldung 🔒",
    featureTitle: "Elixiti Brain",
    featureDesc1: "ist operative Intelligenz für personalintensive Unternehmen.",
    featureDesc2: "Mitarbeiterausfälle in diesen Unternehmen erreichen täglich 15-20% der Belegschaft aufgrund von Krankmeldungen und Urlaub, was Manager oft mehr als 30% ihrer Zeit für den manuellen Ersatz kostet. Die Folge sind operative Fehler und zusätzliche Kosten.",
    validation: "Wir haben das Problem in über 30 Interviews validiert. Das Interesse an einer Pilotnutzung wurde von Unternehmen aus verschiedenen Ländern weltweit bestätigt, was das globale Potenzial unterstreicht.",
    footer: "© 2026 Elixiti d.o.o. | Die Lösung wird derzeit in einer geschlossenen Beta-Phase mit strategichen Partnern getestet.",
    contact: "Kontakt:",
    tableTitle: "Übersicht der öffentlichen Reinigungsausschreibungen in Slowenien",
    tableDesc: "Automatisierte Echtzeit-Überwachung der Daten des Portals e-Naročanje: ein umfassender Überblick über aktuelle Ausschreibungen, teilnehmende Unternehmen und ausgewählte Gewinner im Reinigungssektor.",
    // Funnel Translations
    f1: "1. PROBLEM / INPUT",
    f1a: "ANALYTIK &",
    f1b: "DOKUMENTE",
    f1c: "PERSONAL-",
    f1d: "MANGEL",
    f1e: "RECHTLICHE",
    f1f: "RISIKEN",
    f2: "2. LÖSUNG (ELIXITI AI BRAIN)",
    f2a: "RÖNTGENBLICK",
    f3: "3. ENTSCHEIDUNG",
    f3a: "(BESTÄTIGUNG)",
    f4: "4. AUSFÜHRUNG",
    f4a: "(AUTOMATION)",
    res1a: "HÖHERER",
    res1b: "UMSATZ",
    res2a: "REDUZIERTES",
    res2b: "RISIKO",
    res3a: "ZEIT-",
    res3b: "ERSPARNIS"
  }
};
